import type {
  ForecastCueCard,
  ForecastFollowUpCluster,
  ForecastGroup,
  ForecastPart1Data,
  ForecastPart2Data,
  ForecastPart3Data,
  ForecastPartId,
  ForecastPracticeData,
  ForecastTopic,
} from "@/types/forecast";

const part1Topics: ForecastTopic[] = [
  {
    id: "opportunities",
    name: "Opportunities",
    isNewTopic: true,
    hasNewQuestions: true,
    addedDateLabel: "05/09",
    questions: [
      { id: "opp-1", title: "Did you have any opportunities to take part in new activities as a child?", status: "new" },
      { id: "opp-2", title: "Do you often get new opportunities?", status: "new" },
      { id: "opp-3", title: "Do you like taking on new opportunities?", status: "unanswered" },
      { id: "opp-4", title: "Should people try as many different things as they can?", status: "unanswered" },
    ],
    vocabulary: ["jump at the chance", "step out of my comfort zone", "make the most of"],
  },
  {
    id: "travelling",
    name: "Travelling",
    isNewTopic: false,
    hasNewQuestions: true,
    questions: [
      { id: "trav-1", title: "Did you have a long journey with your family as a child?", status: "unanswered" },
      { id: "trav-2", title: "What transport do you often use when travelling?", status: "new" },
      { id: "trav-3", title: "Do you prefer to sit by the window when travelling?", status: "unanswered" },
      { id: "trav-4", title: "Do you often ride a bicycle?", status: "new" },
    ],
    vocabulary: ["off the beaten track", "a long haul", "travel light"],
  },
  {
    id: "advertisement",
    name: "Advertisement",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "ad-1", title: "Do you like watching advertisements?", status: "unanswered" },
      { id: "ad-2", title: "What kind of advertisements do you find annoying?", status: "unanswered" },
      { id: "ad-3", title: "Do advertisements influence what you buy?", status: "unanswered" },
      { id: "ad-4", title: "Are advertisements on TV different from those online?", status: "unanswered" },
    ],
    vocabulary: ["catch someone's eye", "a hard sell", "brand loyalty"],
  },
  {
    id: "friends",
    name: "Friends",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "fr-1", title: "How often do you meet your friends?", status: "answered" },
      { id: "fr-2", title: "Do you prefer one close friend or many?", status: "answered" },
      { id: "fr-3", title: "What do you and your friends usually do together?", status: "answered" },
      { id: "fr-4", title: "Has your idea of friendship changed since you were a child?", status: "answered" },
    ],
    vocabulary: ["a kindred spirit", "drift apart", "go way back"],
    practiceSummary: {
      answeredCount: 4,
      totalCount: 4,
      lastPracticedLabel: "06/09",
      lowestScoreQuestionTitle: "Do you prefer one close friend or many?",
      latestBand: 6.0,
    },
  },
  {
    id: "politeness",
    name: "Politeness",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "pol-1", title: "Are people in your country generally polite?", status: "unanswered" },
      { id: "pol-2", title: "How do you teach children to be polite?", status: "unanswered" },
      { id: "pol-3", title: "Is politeness more important in some situations than others?", status: "unanswered" },
      { id: "pol-4", title: "Has politeness changed over the years in your country?", status: "unanswered" },
    ],
    vocabulary: ["mind your manners", "come across as rude", "a social norm"],
  },
  {
    id: "rubbish-and-recycling",
    name: "Rubbish and recycling",
    isNewTopic: false,
    hasNewQuestions: true,
    questions: [
      { id: "rub-1", title: "Do you recycle at home?", status: "unanswered" },
      { id: "rub-2", title: "How does your city deal with rubbish?", status: "new" },
      { id: "rub-3", title: "Should people be fined for not recycling?", status: "unanswered" },
      { id: "rub-4", title: "Has recycling become easier in recent years?", status: "unanswered" },
    ],
    vocabulary: ["single-use plastic", "sort your waste", "a landfill"],
  },
  {
    id: "fruit-and-vegetables",
    name: "Fruit and vegetables",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "fv-1", title: "Do you eat enough fruit and vegetables?", status: "answered" },
      { id: "fv-2", title: "What is your favourite fruit?", status: "answered" },
      { id: "fv-3", title: "Do you grow any fruit or vegetables yourself?", status: "answered" },
      { id: "fv-4", title: "Are fruit and vegetables expensive in your country?", status: "answered" },
    ],
    vocabulary: ["a balanced diet", "in season", "locally grown"],
    practiceSummary: {
      answeredCount: 4,
      totalCount: 4,
      lastPracticedLabel: "02/09",
      lowestScoreQuestionTitle: "Are fruit and vegetables expensive in your country?",
      latestBand: 7.0,
    },
  },
  {
    id: "secondary-school",
    name: "Secondary school",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "sec-1", title: "What did you like about your secondary school?", status: "unanswered" },
      { id: "sec-2", title: "What subjects were you good at?", status: "unanswered" },
      { id: "sec-3", title: "Do you still keep in touch with school friends?", status: "unanswered" },
      { id: "sec-4", title: "Would you like to go back and visit your school?", status: "unanswered" },
    ],
    vocabulary: ["a steep learning curve", "extracurricular activities", "reminisce about"],
  },
  {
    id: "shoes",
    name: "Shoes",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "sh-1", title: "How many pairs of shoes do you own?", status: "unanswered" },
      { id: "sh-2", title: "Do you prefer comfort or style when buying shoes?", status: "unanswered" },
      { id: "sh-3", title: "Do you often buy shoes online?", status: "unanswered" },
      { id: "sh-4", title: "Are shoes an important part of an outfit?", status: "unanswered" },
    ],
    vocabulary: ["break in a new pair", "a good fit", "on a budget"],
  },
  {
    id: "lost-and-found",
    name: "Lost and found",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "lf-1", title: "Have you ever lost something valuable?", status: "unanswered" },
      { id: "lf-2", title: "What did you do when you lost it?", status: "unanswered" },
      { id: "lf-3", title: "Have you ever found something that belonged to someone else?", status: "unanswered" },
      { id: "lf-4", title: "Do people usually return lost items in your country?", status: "unanswered" },
    ],
    vocabulary: ["turn up out of the blue", "retrace your steps", "hand it in"],
  },
  {
    id: "computers-tablets",
    name: "Computers / tablets",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "ct-1", title: "How often do you use a computer or tablet?", status: "unanswered" },
      { id: "ct-2", title: "What do you mainly use it for?", status: "unanswered" },
      { id: "ct-3", title: "Did you use computers a lot as a child?", status: "unanswered" },
      { id: "ct-4", title: "Do you think tablets are replacing computers?", status: "unanswered" },
    ],
    vocabulary: ["glued to the screen", "user-friendly", "a game changer"],
  },
];

const part1: ForecastPart1Data = {
  pageTitle: `Part 1 — ${part1Topics.length} topic đời thường`,
  hideAnsweredLabel: "Ẩn câu đã trả lời",
  sortOptions: [
    { id: "newestTopic", label: "Topic mới nhất" },
    { id: "probability", label: "Xác suất ra đề" },
    { id: "unpracticed", label: "Chưa luyện trước" },
  ],
  topics: part1Topics,
};

const part2Groups: ForecastGroup[] = [
  {
    id: "nguoi",
    label: "Người",
    badge: { label: "2 MỚI", variant: "brand" },
    unitCount: 6,
    unitLabel: "đề",
    practicedCount: 3,
    progressLabel: "3/6 đã luyện",
  },
  {
    id: "vat",
    label: "Vật",
    unitCount: 7,
    unitLabel: "đề",
    practicedCount: 2,
    progressLabel: "2/7 đã luyện",
  },
  {
    id: "hoat-dong",
    label: "Hoạt động",
    badge: { label: "HAY RA", variant: "warning" },
    unitCount: 4,
    unitLabel: "đề",
    practicedCount: 3,
    progressLabel: "3/4 đã luyện",
  },
  {
    id: "dia-diem",
    label: "Địa điểm",
    unitCount: 3,
    unitLabel: "đề",
    practicedCount: 0,
    progressLabel: "chưa luyện đề nào",
  },
];

const part2CueCards: Record<string, ForecastCueCard[]> = {
  nguoi: [
    {
      id: "old-person-you-admire",
      groupId: "nguoi",
      tag: { label: "HAY RA", variant: "warning" },
      title: "Describe an old person you admire",
      prompts: ["who this person is", "how you know them", "what they usually do", "and explain why you admire them."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["a wealth of experience", "look up to", "pass down"],
      followUpCount: 3,
      sidebarMetaLabel: "14 lần/30 ngày",
      rowMetaLabel: "14 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
    {
      id: "person-protects-environment",
      groupId: "nguoi",
      tag: { label: "ĐỀ MỚI", variant: "brand" },
      title: "Describe a person who helps to protect the environment",
      prompts: ["who this person is", "what they do to protect the environment", "how you know them", "and explain how you feel about what they do."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["raise awareness", "lead by example", "a ripple effect"],
      followUpCount: 2,
      sidebarMetaLabel: "9 lần/30 ngày",
      rowMetaLabel: "vào bộ 02/09 · 9 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
    {
      id: "someone-older-you-admire",
      groupId: "nguoi",
      title: "Describe someone older than you that you admire",
      prompts: ["who this person is", "how long you have known them", "what qualities they have", "and explain why you admire them."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["set in their ways", "quietly resilient", "a role model"],
      followUpCount: 2,
      sidebarMetaLabel: "đã luyện 2 lần",
      rowMetaLabel: "đã luyện 2 lần · 05/09",
      statusLabel: "đã luyện 2 lần",
      practiceSummary: { practicedCount: 2, latestBand: 6.0 },
    },
    {
      id: "person-achieved-something-difficult",
      groupId: "nguoi",
      title: "Describe a person you know who achieved something difficult",
      prompts: ["who this person is", "what they achieved", "how they achieved it", "and explain how you feel about their achievement."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["against all odds", "sheer determination", "pay off"],
      followUpCount: 3,
      sidebarMetaLabel: "đã luyện 1 lần",
      rowMetaLabel: "đã luyện 1 lần · 31/08",
      statusLabel: "đã luyện 1 lần",
      practiceSummary: { practicedCount: 1, latestBand: 7.0 },
    },
    {
      id: "person-taught-new-skill",
      groupId: "nguoi",
      title: "Describe a person who taught you a new skill",
      prompts: ["who this person is", "what skill they taught you", "how they taught you", "and explain how useful this skill is."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["hands-on experience", "pass down", "come in handy"],
      followUpCount: 2,
      sidebarMetaLabel: "6 lần/30 ngày",
      rowMetaLabel: "6 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
    {
      id: "famous-person-local-area",
      groupId: "nguoi",
      title: "Describe a famous person in your local area",
      prompts: ["who this person is", "how you know about them", "what they are known for", "and explain what you think of them."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["a household name", "make a name for yourself", "well-regarded"],
      followUpCount: 2,
      sidebarMetaLabel: "4 lần/30 ngày",
      rowMetaLabel: "4 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
  ],
  vat: [
    {
      id: "object-you-find-useful",
      groupId: "vat",
      tag: { label: "ĐỀ MỚI", variant: "brand" },
      title: "Describe an object you find useful in your daily life",
      prompts: ["what it is", "how long you have had it", "how you use it", "and explain why it is useful to you."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["come in handy", "indispensable", "a lifesaver"],
      followUpCount: 2,
      sidebarMetaLabel: "vào bộ 08/09 · 6 lần/30 ngày",
      rowMetaLabel: "vào bộ 08/09 · 6 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
    {
      id: "technology-difficult-to-use",
      groupId: "vat",
      title: "Describe a piece of technology you find difficult to use",
      prompts: ["what it is", "when you started using it", "what difficulties you have with it", "and explain why you find it difficult."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["user-unfriendly", "a steep learning curve", "glitchy"],
      followUpCount: 3,
      sidebarMetaLabel: "đã luyện 1 lần",
      rowMetaLabel: "đã luyện 1 lần · 20/08",
      statusLabel: "đã luyện 1 lần",
      practiceSummary: { practicedCount: 1, latestBand: 6.5 },
    },
  ],
  "hoat-dong": [
    {
      id: "hobby-you-enjoy",
      groupId: "hoat-dong",
      tag: { label: "HAY RA", variant: "warning" },
      title: "Describe a hobby you enjoy in your free time",
      prompts: ["what the hobby is", "how you started it", "how often you do it", "and explain why you enjoy it."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["unwind", "an outlet for creativity", "get hooked on"],
      followUpCount: 3,
      sidebarMetaLabel: "12 lần/30 ngày",
      rowMetaLabel: "12 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
    {
      id: "activity-you-do-to-relax",
      groupId: "hoat-dong",
      title: "Describe an activity you do to relax",
      prompts: ["what the activity is", "when you do it", "who you do it with", "and explain how it helps you relax."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["unwind", "clear your head", "recharge"],
      followUpCount: 2,
      sidebarMetaLabel: "đã luyện 3 lần",
      rowMetaLabel: "đã luyện 3 lần · 03/09",
      statusLabel: "đã luyện 3 lần",
      practiceSummary: { practicedCount: 3, latestBand: 6.5 },
    },
  ],
  "dia-diem": [
    {
      id: "quiet-place",
      groupId: "dia-diem",
      title: "Describe a quiet place you like to spend time in",
      prompts: ["where it is", "how often you go there", "what you do there", "and explain why you like it."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["a hidden gem", "unwind", "away from the hustle and bustle"],
      followUpCount: 2,
      sidebarMetaLabel: "5 lần/30 ngày",
      rowMetaLabel: "5 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
    {
      id: "place-to-visit",
      groupId: "dia-diem",
      title: "Describe a place you would like to visit in the future",
      prompts: ["where it is", "how you know about it", "what you would do there", "and explain why you want to visit it."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["top of my bucket list", "off the beaten track", "breathtaking"],
      followUpCount: 2,
      sidebarMetaLabel: "4 lần/30 ngày",
      rowMetaLabel: "4 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
    {
      id: "hometown",
      groupId: "dia-diem",
      title: "Describe your hometown",
      prompts: ["where it is", "what it is famous for", "what you like about it", "and explain how it has changed."],
      prepMinutes: 1,
      speakMinutes: 2,
      vocabulary: ["a stone's throw from", "up-and-coming", "close-knit community"],
      followUpCount: 2,
      sidebarMetaLabel: "3 lần/30 ngày",
      rowMetaLabel: "3 lần/30 ngày",
      statusLabel: "chưa luyện",
    },
  ],
};

const part2: ForecastPart2Data = {
  pageTitle: "Bộ đề dự đoán 09 → 12/2026",
  hideAnsweredLabel: "Ẩn đề đã luyện",
  groups: part2Groups,
  cueCardsByGroup: part2CueCards,
};

const part3Groups: ForecastGroup[] = [
  {
    id: "nguoi",
    label: "Người",
    unitCount: 3,
    unitLabel: "chùm",
    practicedCount: 2,
    progressLabel: "2/3 đã trả lời",
  },
  {
    id: "vat",
    label: "Vật",
    badge: { label: "1 MỚI", variant: "brand" },
    unitCount: 4,
    unitLabel: "chùm",
    practicedCount: 1,
    progressLabel: "1/4 đã trả lời",
  },
  {
    id: "hoat-dong",
    label: "Hoạt động",
    unitCount: 2,
    unitLabel: "chùm",
    practicedCount: 1,
    progressLabel: "1/2 đã trả lời",
  },
  {
    id: "dia-diem",
    label: "Địa điểm",
    unitCount: 1,
    unitLabel: "chùm",
    practicedCount: 0,
    progressLabel: "chưa trả lời",
  },
];

const part3Clusters: Record<string, ForecastFollowUpCluster[]> = {
  nguoi: [
    {
      id: "cluster-old-person",
      groupId: "nguoi",
      sourceTitle: "Describe an old person you admire",
      questions: [
        { id: "p3-op-1", title: "Do young people respect the elderly as much as before?", status: "answered" },
        { id: "p3-op-2", title: "What can older generations teach younger ones?", status: "answered" },
        { id: "p3-op-3", title: "Should families live together across generations?", status: "answered" },
      ],
      sidebarMetaLabel: "3/3 câu",
      practiceSummary: {
        answeredCount: 3,
        totalCount: 3,
        lastPracticedLabel: "05/09",
        lowestScoreQuestionTitle: "Should families live together across generations?",
        latestBand: 6.0,
      },
    },
    {
      id: "cluster-helped-someone",
      groupId: "nguoi",
      sourceTitle: "Describe a time you helped someone who was in trouble",
      questions: [
        { id: "p3-hs-1", title: "Should schools teach students how to help others?", status: "answered" },
        { id: "p3-hs-2", title: "Are people less willing to help strangers nowadays?", status: "answered" },
      ],
      sidebarMetaLabel: "2/2 câu",
      practiceSummary: {
        answeredCount: 2,
        totalCount: 2,
        lastPracticedLabel: "01/09",
        lowestScoreQuestionTitle: "Are people less willing to help strangers nowadays?",
        latestBand: 6.5,
      },
    },
    {
      id: "cluster-famous-person",
      groupId: "nguoi",
      sourceTitle: "Describe a famous person in your local area",
      questions: [
        { id: "p3-fp-1", title: "Why do people admire famous figures?", status: "unanswered" },
        { id: "p3-fp-2", title: "Does fame always bring a good influence?", status: "unanswered" },
      ],
      sidebarMetaLabel: "2 câu · chưa trả lời",
      tipText: "Part 3 chấm ý và lập luận — mỗi câu nên có 1 ví dụ cụ thể.",
    },
  ],
  vat: [
    {
      id: "cluster-technology-problem",
      groupId: "vat",
      sourceTitle: "A problem of technology you have encountered, like a computer or a cell phone",
      questions: [
        { id: "p3-tech-1", title: "What kinds of technological problems do people often face?", status: "unanswered" },
        { id: "p3-tech-2", title: "Do older people have more difficulty using technology than young people?", status: "unanswered" },
        { id: "p3-tech-3", title: "Do you think people depend too much on technology nowadays?", status: "unanswered" },
      ],
      sidebarBadge: { label: "3 CÂU", variant: "neutral" },
      sidebarMetaLabel: "chưa trả lời",
    },
    {
      id: "cluster-movie-dont-like",
      groupId: "vat",
      sourceTitle: "A movie / film you don't like",
      questions: [
        { id: "p3-mov-1", title: "Do people's movie preferences change as they get older?", status: "unanswered" },
        { id: "p3-mov-2", title: "Should documentary films be completely truthful?", status: "unanswered" },
        { id: "p3-mov-3", title: "Can movies help people understand a country's culture?", status: "unanswered" },
      ],
      sidebarMetaLabel: "3 câu · chưa trả lời",
      tipText: "Part 3 chấm ý và lập luận — mỗi câu nên có 1 ví dụ cụ thể.",
    },
    {
      id: "cluster-public-building",
      groupId: "vat",
      sourceTitle: "A public building you enjoy visiting (e.g. a library, a shopping mall)",
      questions: [
        { id: "p3-pb-1", title: "Why do people enjoy spending time in public buildings?", status: "answered" },
        { id: "p3-pb-2", title: "How has the design of public buildings changed?", status: "answered" },
        { id: "p3-pb-3", title: "Should the government invest more in public spaces?", status: "answered" },
      ],
      sidebarBadge: { label: "band 5.5", variant: "warning" },
      sidebarMetaLabel: "3/3 câu",
      practiceSummary: {
        answeredCount: 3,
        totalCount: 3,
        lastPracticedLabel: "07/09",
        lowestScoreQuestionTitle: "Should the government invest more in public spaces?",
        latestBand: 5.5,
      },
    },
    {
      id: "cluster-book-happy",
      groupId: "vat",
      sourceTitle: "A book you read that made you happy",
      questions: [
        { id: "p3-book-1", title: "Do people read for pleasure as much as before?", status: "unanswered" },
        { id: "p3-book-2", title: "Can books influence a person's mood?", status: "unanswered" },
      ],
      sidebarMetaLabel: "2 câu · chưa trả lời",
    },
  ],
  "hoat-dong": [
    {
      id: "cluster-hobby",
      groupId: "hoat-dong",
      sourceTitle: "Describe a hobby you enjoy in your free time",
      questions: [
        { id: "p3-hob-1", title: "Why do people need hobbies?", status: "answered" },
        { id: "p3-hob-2", title: "Do hobbies change as people get older?", status: "answered" },
      ],
      sidebarMetaLabel: "2/2 câu",
      practiceSummary: {
        answeredCount: 2,
        totalCount: 2,
        lastPracticedLabel: "03/09",
        lowestScoreQuestionTitle: "Do hobbies change as people get older?",
        latestBand: 6.5,
      },
    },
    {
      id: "cluster-relax-activity",
      groupId: "hoat-dong",
      sourceTitle: "Describe an activity you do to relax",
      questions: [
        { id: "p3-rel-1", title: "Why is it important for people to relax?", status: "unanswered" },
        { id: "p3-rel-2", title: "Do you think modern life is more stressful than before?", status: "unanswered" },
      ],
      sidebarMetaLabel: "2 câu · chưa trả lời",
      tipText: "Part 3 chấm ý và lập luận — mỗi câu nên có 1 ví dụ cụ thể.",
    },
  ],
  "dia-diem": [
    {
      id: "cluster-quiet-place",
      groupId: "dia-diem",
      sourceTitle: "Describe a quiet place you like to spend time in",
      questions: [
        { id: "p3-qp-1", title: "Why do people need quiet places nowadays?", status: "unanswered" },
        { id: "p3-qp-2", title: "Are quiet places disappearing in big cities?", status: "unanswered" },
      ],
      sidebarMetaLabel: "2 câu · chưa trả lời",
    },
  ],
};

const part3: ForecastPart3Data = {
  pageTitle: "Part 3 nối tiếp theo nhóm chủ đề",
  hideAnsweredLabel: "Ẩn câu đã trả lời",
  groups: part3Groups,
  clustersByGroup: part3Clusters,
};

const customTopics: ForecastTopic[] = [
  {
    id: "cau-ban-them",
    name: "Câu bạn đã thêm",
    isNewTopic: false,
    hasNewQuestions: false,
    questions: [
      { id: "cus-1", title: "Do you think social media brings people closer or further apart?", status: "unanswered" },
      { id: "cus-2", title: "What's a habit you'd like to change?", status: "unanswered" },
    ],
    vocabulary: ["a double-edged sword", "break a habit"],
  },
];

const custom: ForecastPart1Data = {
  pageTitle: "Câu bạn thêm",
  hideAnsweredLabel: "Ẩn câu đã trả lời",
  sortOptions: [
    { id: "newestTopic", label: "Mới thêm nhất" },
    { id: "unpracticed", label: "Chưa luyện trước" },
  ],
  topics: customTopics,
};

export function getForecastPracticeMockData(): ForecastPracticeData {
  const parts: Record<ForecastPartId, number> = {
    part1: part1Topics.length,
    part2: part2Groups.reduce((sum, group) => sum + group.unitCount, 0),
    part3: part3Groups.reduce((sum, group) => sum + group.unitCount, 0),
    custom: customTopics.length,
  };

  return {
    quarterLabel: "Luyện Forecast · Quý 3/2026",
    parts: [
      { id: "part1", label: "Part 1", count: parts.part1 },
      { id: "part2", label: "Part 2", count: parts.part2 },
      { id: "part3", label: "Part 3", count: parts.part3 },
      { id: "custom", label: "Câu bạn thêm", count: parts.custom },
    ],
    part1,
    part2,
    part3,
    custom,
  };
}
